# Generated by Django 4.2.27 on 2026-02-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_blogpost_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("speaker", "🎤 Speaker"),
                            ("panelist", "👥 Panelist"),
                            ("attendee", "Attendee"),
                        ],
                        default="attendee",
                        max_length=20,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        help_text="Talk/panel topic if speaker",
                        max_length=300,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="conferences/"),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "-date"],
            },
        ),
        migrations.CreateModel(
            name="Hackathon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("winner", "🏆 Winner"),
                            ("runner_up", "🥈 Runner-up"),
                            ("finalist", "🎯 Finalist"),
                            ("participant", "Participant"),
                            ("mentor", "Mentor"),
                            ("judge", "Judge"),
                        ],
                        default="participant",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="hackathons/"),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "project_link",
                    models.URLField(
                        blank=True, help_text="Link to project or demo", null=True
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "-date"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("native", "Native"),
                            ("fluent", "Fluent"),
                            ("intermediate", "Intermediate"),
                            ("basic", "Basic"),
                        ],
                        default="fluent",
                        max_length=20,
                    ),
                ),
                (
                    "flag_code",
                    models.CharField(
                        blank=True,
                        help_text="Country code for flag, e.g., 'fr' for French",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LeadershipActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=200)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("training", "📚 Training Program"),
                            ("mentoring", "🎓 Mentoring"),
                            ("volunteering", "🤝 Volunteering"),
                            ("fellowship", "⭐ Fellowship"),
                            ("recognition", "🏅 Recognition"),
                        ],
                        default="training",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="leadership/"),
                ),
                ("description", models.TextField(blank=True)),
                ("link", models.URLField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Leadership Activity",
                "verbose_name_plural": "Leadership Activities",
                "ordering": ["order", "-start_date"],
            },
        ),
        migrations.AddField(
            model_name="certification",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Badge or logo image",
                null=True,
                upload_to="certifications/",
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="verification_link",
            field=models.URLField(
                blank=True, help_text="Link to verify certification", null=True
            ),
        ),
    ]
